/*
Code supplied by  Barton Willis.
Modified slightly by John Lapeyre.
*/

/* These do not appear to be used
conjsimp (e) := block([args],
  if mapatom(e) then e
  elseif ?mtimesp(e) then (
    args : args(e),
    for p in args do e : ratsubst('abs(p)^2, p * conjugate(p),e),
    e)
  else apply(op(e), map('conjsimp, args(e))));

inargs(e) := block([inflag:true],args(e));
inop(e) := block([inflag:true],op(e));
*/

/* End of code supplied by  Barton Willis */
